services:
  - type: web
    name: planning-poker
    env: node
    plan: starter
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    
  - type: redis
    name: planning-poker-redis
    plan: free
    region: oregon
    maxmemoryPolicy: allkeys-lru 